apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rds.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "rds.name" . }}
    chart: {{ include "rds.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    keel.sh/policy: {{ .Values.keel.policy  }}
    keel.sh/trigger: {{ .Values.keel.trigger  }}
    keel.sh/approvals: {{ .Values.keel.approvals | quote }}
  annotations:
    keel.sh/pollSchedule: {{ .Values.keel.pollSchedule | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "rds.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "rds.name" . }}
        release: {{ .Release.Name }}
      annotations:
    {{ toYaml .Values.podAnnotations | indent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: {{ include "rds.fullname" . }}-config
              mountPath: /etc/nginx/
              subPath: nginx.conf
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          {{- if .Values.livenessProbe }}
          livenessProbe:
          {{ toYaml .Values.livenessProbe | indent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
      {{ toYaml .Values.readinessProbe | indent 12 }}
      {{- end }}
      restartPolicy: Always
      serviceAccountName: {{ template "rds.serviceAccountName" . }}
      securityContext:
      {{ toYaml .Values.securityContext | indent 8 }}
      volumes:
        - name: {{ include "rds.fullname" . }}-config
          configMap:
            name: {{ include "rds.fullname" . }}-config

