{{- if and .Values.hazelcast.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "spring.fullname" . }}-hazelcast
  namespace: {{ .Release.Namespace | quote }}
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  labels:
    app: {{ template "spring.name" . }}-hazelcast
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: hazelcast
      port: {{ .Values.hazelcast.port }}
      targetPort: {{ .Values.hazelcast.port }}
  selector:
    app: {{ template "spring.name" . }}
    release: {{ .Release.Name | quote }}
{{- end -}}