#generic
namespace: ""
appName: ""
nameOverride: "test"
fullnameOverride: "tes"

curlStatement: "curl -v -X POST --user $BASIC_AUTH_ADMIN_USERNAME:$BASIC_AUTH_ADMIN_PASSWORD --header 'Content-Type: application/json' --header 'Accept: application/json'"
baseUrl: "http://entrnce-deal-platform.{namespace}:8080/api/applicationEvents/"

scheduleOffset: "utcsummertime"

# Voorbeeld: Als je wilt dat een job om 13:30 lokale tijd gedraaid moet worden vul
# je in de trigger schedule het volgende in: 0 30 11 * * *
# dus altijd lokale tijd min 2 uur.

#specific per template
triggers:
  # notification triggers
  - trigger: 'CheckBidFileSent'
    type: "notificationTrigger"
    schedule: "45 8 * * *"
  - trigger: "CheckBidConfirmationReceived"
    type: "notificationTrigger"
    schedule: "36 11 * * *"
  - trigger: "CheckPricesAvailable"
    type: "notificationTrigger"
    schedule: "10 11 * * *"
  - trigger: "CheckEnecoEpexSpotPricesAvailable"
    type: "notificationTrigger"
    schedule: "5 14 * * *"
  - trigger: "CheckPreEProgramSent"
    type: "notificationTrigger"
    schedule: "40 8 * * *"

secretKeyRefEnv: {}
#  secretname:
#    - mysql-password: MYSQL_PASSWORD
