#generic
namespace: "exe-deploy"
appName: "entrnce"
nameOverride: ""
fullnameOverride: ""

curlStatement: "curl -v -X POST --user $basic-auth-admin-username:$basic-auth-admin-password --header 'Content-Type: application/json' --header 'Accept: application/json'"
baseUrl: "https://google.com/"

scheduleOffset: "utcsummertime"

# Voorbeeld: Als je wilt dat een job om 13:30 lokale tijd gedraaid moet worden vul
# je in de trigger schedule het volgende in: 0 30 11 * * *
# dus altijd lokale tijd min 2 uur.

triggers: {}
  # - trigger: '?test'
  #   type: "search"
  #   schedule: "45 * * * *"
#  - trigger: "CheckBidConfirmationReceived"
#    type: "notificationTrigger"
#    schedule: "36 11 * * *"

secretKeyRefEnv: {}
#  secretname:
#    - basic-auth-admin-username: BASIC_AUTH_ADMIN_USERNAME
#    - basic-auth-admin-password: BASIC_AUTH_ADMIN_PASSWORD
