#generic
namespace: "cluster-ops"
appName: "entrnce-cronjob"
nameOverride: ""
fullnameOverride: ""

successfulJobsHistoryLimit: 3
failedJobsHistoryLimit: 3

image: "350124346922.dkr.ecr.eu-central-1.amazonaws.com/entrnce/exe-analytics:master"

# Voorbeeld: Als je wilt dat een job om 13:30 lokale tijd gedraaid moet worden vul
# je in de trigger schedule het volgende in: 0 30 11 * * *
# dus altijd lokale tijd min 2 uur.

triggers: {}
# triggers:
#   - name: 'Futures'
#     command: "python /src/entrnce_price_curve/epc1_futures.py"
#     schedule: "0 3 * * *"
#   - name: 'PriceCurve'
#     command: "/src/entrnce_price_curve/epc2_entrnce_price_curve.py"
#     schedule: "15 3 * * *"
#   - name: 'FinanceChecks'
#     command: "/src/entrnce_checks/entrnce_checks.py"
#     schedule: "0 6 * * *"

extraEnv: {}
# extraEnv:
  ## Extra environment variables to be injected
  # DATABASE_ENGINE: mysql
  # DATABASE_HOST: mysql
  # DATABASE_NAME: spring
  # DATABASE_USERNAME: spring
  # DATABASE_PASSWORD: spring

secretKeyRefEnv: {}
# secretKeyRefEnv:
#   secretname:
#     - mysql-password: MYSQL_PASSWORD

secrets: {}
# secrets:
#   finance:
#     - amazon-aws-s3-access-key: amazon-aws-s3-access-key
#     - amazon-aws-s3-secret-key: amazon-aws-s3-secret-key

cluster:
  name: entrnce-eks

settings:
  enabled: false
  name: config-volume
  path: /settings/settings.yaml
  subPath: settings.yml
  data: |-
    ---
    logging:
      level:
        root: WARN

persistentVolume:
  enabled: false
  name: transaction-logs
  path: /app/transaction-logs
  storage: 1Gi
  storageClassName: gp2