apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "keycloak.name" . }}
    chart: {{ include "keycloak.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "keycloak.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "keycloak.name" . }}
        release: {{ .Release.Name }}
      {{- if .Values.podAnnotations }}
      annotations:
      {{ toYaml .Values.podAnnotations | indent 8 }}
    {{ end }}
    spec:
      serviceAccountName: {{ template "keycloak.serviceAccountName" . }}
      {{- if  .Values.securityContext }}
      securityContext:
      {{ toYaml .Values.securityContext | indent 8 }}
      {{ end }}
      containers:
        - name:  {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
            - -b=$(POD_IP)
            - -bprivate=$(POD_IP)
            - -bmanagement=127.0.0.1
            - --server-config=standalone-ha.xml
          env:
            {{- range $secretKeyRefEnvKey, $secretKeyRefEnvValue := .Values.secretKeyRefEnv }}
            {{- range $secretName, $secretValue := $secretKeyRefEnvValue }}
            {{- range $key, $value := $secretValue }}
            - name: {{ $value }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretKeyRefEnvKey}}
                  key: {{ $key }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- range $key, $value := .Values.extraEnv }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
            - containerPort: 7600
              protocol: TCP
              name: jgroups-tcp
            - containerPort: 57600
              protocol: TCP
              name: jgroups-tcp-fd
            - containerPort: 55200
              protocol: UDP
              name: jgroups-udp
            - containerPort: 54200
              protocol: UDP
              name: jgroups-udp-fd
            - containerPort: 9990
              protocol: TCP
              name: management
          {{- if .Values.livenessProbe }}
          livenessProbe:
          {{ toYaml .Values.livenessProbe | indent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
          {{ toYaml .Values.readinessProbe | indent 12 }}
          {{- end }}
          resources:
      {{ toYaml .Values.resources | indent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{ toYaml . | indent 8 }}
      {{- end }}
      volumes:
        - name: data
          emptyDir: {}
        {{- if hasKey .Values.keycloak.config "secretName" }}
        - name: secret-file
          secret:
            secretName: {{ .Values.keycloak.config.secretName }}
      {{- end }}
      imagePullSecrets:
        - name: {{ .Values.imageCredentials.name }}
