{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Namespace }}-{{ template "keycloak.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "keycloak.name" . }}
    chart: {{ template "keycloak.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups: [ "" ]
    resources: [ "services", "pods", "endpoints", "configmaps" ]
    verbs: [ "get","list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}-{{ template "keycloak.fullname" . }}
  labels:
    app: {{ template "keycloak.name" . }}
    chart: {{ template "keycloak.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Namespace }}-{{ template "keycloak.fullname" . }}
subjects:
  - name: {{ .Release.Namespace }}-{{ template "keycloak.fullname" . }}
    namespace: {{ .Release.Namespace | quote }}
    kind: ServiceAccount
  {{- end -}}
