apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: {{ include "oauth2-proxy.name" . }}
  name: {{ include "oauth2-proxy.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector:
    k8s-app: {{ include "oauth2-proxy.name" . }}