replicaCount: 1

image:
  repository: nickhartjes/dummy-container
  tag: latest
  pullPolicy: Always
imageCredentials:
  name: private-docker-registry

## The list of ports that your app listens on
containerPort: 80

nameOverride: ""
fullnameOverride: ""

keel:
  # keel policy (all/major/minor/patch/force)
  policy: force
  # trigger type, defaults to events such as pubsub, webhooks
  trigger: poll
  # polling schedule
  pollSchedule: "@every 1m"
  # approvals required to proceed with an update
  approvals: 1
  # only makes a difference when used with 'force' policy, will only update if tag matches :dev->:dev, :prod->:prod
  match-tag: true


podAnnotations: {}
#  prometheus.io/scrape: "true"
#  prometheus.io/path: "/actuator/prometheus"

service:
  enabled: true
  httpPort: 80
  ## If service.type is not set to NodePort, the following statement
  ## will be ignored.
  ##
  # nodePort: 32015

  ## Service type can be set to ClusterIP, NodePort or LoadBalancer.
  ##
  type: ClusterIP

  ## Service annotations
  ##
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
  #   service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:xx-xxxx-x:xxxxxxxxxxx:certificate/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx
  #   external-dns.alpha.kubernetes.io/hostname: drone.domain.tld.

ingress:
  ## If true, Ingress will be created.
  ##
  enabled: false

  ## Ingress annotations
  ##
  # annotations:
  #   kubernetes.io/ingress.class: gce
  #   kubernetes.io/ingress.class: nginx
  #   kubernetes.io/tls-acme: 'true'

  ## hostnames must be provided if Ingress is enabled
  ##
  # hosts:
  #   - spring.example.io

  ## Ingress TLS configuration secrets
  ## Must be manually created in the namespace
  ##
  # tls:
  #   - secretName: spring-tls
  #     hosts:
  #       - spring.example.io

serviceAccount:
  create: true
  # name: ~

rbac:
  create: true

## uncomment and modify the following livenessProbe and readinessProbe.
## These defaults should work with anything that uses the spring health actuator.
livenessProbe: {}
#  httpGet:
#    path: /actuator/health
#    port: http
#  initialDelaySeconds: 300
#  periodSeconds: 10
readinessProbe: {}
#  httpGet:
#    path: /actuator/health
#    port: http
#  initialDelaySeconds: 60
#  periodSeconds: 10


nginx: {}
#  defaultconf:

#entrnce: {}
#  config01:
#  config02:

# Example:
#entrnce:
#  config01:
#    {
#      "redirectUrlAfterLogin": "insight",
#      "locale": "de-DE",
#      "frontEndPathPrefix": "customer",
#      "timezone": "Europe/Amsterdam",
#      "endPoints": {
#        "user": "/api/customer-matcher",
#        "backend": "/api/customer-matcher",
#        "auth": "/oidc",
#        "public": "/api/customer-matcher/public"
#      },
#      "sentryDsn": "https://1c33bae7c12944b2b703347a9f539522:8329f0ab24b2411ca4ab8ee435f374f3@sentry.e-x-e.cloud/23"
#    }
#  config02:
#    {
#      "redirectUrlAfterLogin": "",
#      "locale": "de-DE",
#      "frontEndPathPrefix": "stadtwerke",
#      "timezone": "Europe/Amsterdam",
#      "endPoints": {
#        "user": "/api/stadtwerke-matcher",
#        "backend": "/api/stadtwerke-matcher",
#        "auth": "/oidc",
#        "public": "/api/stadtwerke-matcher/public"
#      },
#      "sentryDsn": "https://1c33bae7c12944b2b703347a9f539522:8329f0ab24b2411ca4ab8ee435f374f3@sentry.e-x-e.cloud/23"
#    }


entrnce:
  config-customer.json:
    {
      "locale": "nl-NL",
      "timezone": "Europe/Amsterdam",
      "showTutorial": true,
      "endPoints": {
        "public": "/api/public",
        "user": "/api/my-deal-platform/",
        "dealPlatform": "/api/my-deal-platform/",
        "auth": "/oidc/",
        "entrnceCms": ""
      },
      "sentryDsn": "https://f5450944a7224e6d911462af1e7b783c@sentry.e-x-e.cloud/10"
    }
  config-public.json:
    {
      "locale": "nl-NL",
      "timezone": "Europe/Amsterdam",
      "endPoints": {
        "public": "/api/public",
        "user": "/api/my-deal-platform/",
        "dealPlatform": "/api/my-deal-platform/",
        "auth": "/oidc/",
        "entrnceCms": ""
      },
      "sentryDsn": "https://f5450944a7224e6d911462af1e7b783c@sentry.e-x-e.cloud/10"
    }
  config-admin.json:
    {
      "locale": "nl-NL",
      "timezone": "Europe/Amsterdam",
      "showSampleActions": true,
      "endPoints": {
        "user": "/api/deal-platform/",
        "dealPlatform": "/api/deal-platform/",
        "auth": "/oidc/"
      },
      "ebaseUsageStartDate": "2017-07-31T00:00:00+02:00",
      "sentryDsn": "https://f5450944a7224e6d911462af1e7b783c@sentry.e-x-e.cloud/10"
    }
