apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "angular.fullname" . }}-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "angular.name" . }}
    chart: {{ include "angular.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- if hasKey .Values.nginx "defaultconf" }}
  default.conf: |
    {{ .Values.nginx.defaultconf | b64enc }}
    {{ end }}
  {{- if hasKey .Values.entrnce "config01" }}
  config01.json: |
    {{ .Values.nginx.defaultconf | toJson | quote }}
    {{ end }}
  {{- if hasKey .Values.entrnce "config02" }}
  config02.json: |
    {{ .Values.nginx.defaultconf | toJson | quote }}
    {{ end }}
