apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "angular.fullname" . }}-conf.d
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "angular.name" . }}
    chart: {{ include "angular.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  default.conf: |
    {{ .Files.Get "files/default.conf" | b64enc }}
  {{- range $path, $d := .Files.Glob "files/json/**.json" }}
    {{ $path }}: |-
    {{- $d | toString | nindent 4 }}
  {{ end }}
  {{- range $path, $d := .Files.Glob "files/conf/**.conf" }}
    {{ $path }}: |-
    {{- $d | toString }}
  {{ end }}


