apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "angular.fullname" . }}-default.conf
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "angular.name" . }}
    chart: {{ include "angular.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{ if .Files.Get "config/default.conf" }}
  default.conf: {{ .Files.Get "config/default.conf"| b64enc }}
  {{ end }}
