apiVersion: v1
description: A helm chart to deploy OpenVPN on Entrnce cluster without hacking to get it work
name: openvpn
version: 0.0.4
maintainers:
- name: Wilco ten Wolde
icon: https://forums.openvpn.net/styles/openvpn/theme/images/ovpnlogo.png
keywords:
- openvpn
- vpn
- tunnel
- network
- service
- connectivity
- encryption
home: https://openvpn.net/index.php/open-source.html
sources:
- https://github.com/jfelten/openvpn-docker
- https://github.com/kubernetes/charts/tree/master/stable/openvpn
- https://github.com/jfelten/helm-charts
