{{- if .Values.configmap.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.name }}
data:
  application.properties: |
    work.conf={{ .Values.configmap.conf }}
    work.title={{ .Values.configmap.title }}
{{- end }}