apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: wilco-test-app
          imagePullPolicy: {{ .Values.pullPolicy }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.springprofile }}
          image: {{ .Values.image.repository }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /app/config/
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ .Values.name }}