apiVersion: v2
description: Helm chart for deploying trader-cronjobs for Entrnce
name: trader-cronjobs
keywords:
  - trader-cronjobs
home: https://entrnce.com/
version: 0.0.7
maintainers:
  - name: Nick Hartjes
    email: nick.hartjes@entrnce.com
  - name: Nick Hol
    email: nick.hol@entrnce.com