{{ if .Values.settings.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cronjobs.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "cronjobs.name" . }}
    chart: {{ include "cronjobs.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  settings.yml:
    {{ toYaml .Values.settings.data | indent 4  }}
{{ end }}