{{ if .Values.persistentVolume.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentVolume.name }}
  labels:
    app: {{ include "cronjobs.name" . }}
    chart: {{ include "cronjobs.chart" . }}
    release: {{ .Release.Name  }}
    heritage: {{ .Release.Service }}
    scheduleOffset: {{ .Values.scheduleOffset }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolume.storage }}
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
{{ end }}