apiVersion: v1
appVersion: 0.0.3.BUILD-SNAPSHOT
description: Helm chart for deploying basic Spring Boot applications
name: spring-boot
keywords:
- spring
- spring-cloud
- spring-boot
home: https://spring.io
icon: https://spring.io/img/homepage/icon-spring-boot.svg
version: 0.0.3
maintainers:
  - name: Nick Hartjes
    email: nick.hartjes@entrnce.com
