apiVersion: v1
description: Helm chart for deploying analytics- for Entrnce
name: analytics-cronjobs
keywords:
  - analytics-cronjobs
home: https://entrnce.com/
version: 0.0.1
maintainers:
  - name: Nick Hartjes
    email: nick.hartjes@entrnce.com
